# Generated by Django 3.2.14 on 2022-07-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=10)),
                ('lastName', models.CharField(default='', max_length=10)),
                ('userName', models.CharField(default='', max_length=10, unique=True)),
                ('password', models.CharField(default='', max_length=10)),
                ('login_loc', models.CharField(default='', max_length=10, unique=True)),
                ('login_time', models.IntegerField(default=1)),
            ],
        ),
    ]
