# Generated by Django 3.2.14 on 2022-07-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_loc',
            field=models.CharField(default='', max_length=140, unique=True),
        ),
    ]
